../../verilog/tb/configure.sv
../../verilog/constants.sv
../../verilog/functions.sv
../../verilog/wires.sv
../../verilog/alu.sv
../../verilog/agu.sv
../../verilog/bcu.sv
../../verilog/lsu.sv
../../verilog/csr_alu.sv
../../verilog/div.sv
../../verilog/mul.sv
../../verilog/predecoder.sv
../../verilog/postdecoder.sv
../../verilog/register.sv
../../verilog/csr.sv
../../verilog/compress.sv
../../verilog/prefetch.sv
../../verilog/forwarding.sv
../../verilog/fetch_stage.sv
../../verilog/execute_stage.sv
../../verilog/arbiter.sv
../../verilog/clint.sv
../../verilog/clic.sv
../../verilog/cpu.sv
../../verilog/tb/bram.sv
../../verilog/tb/print.sv
../../verilog/tb/soc.sv
